fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: python
    hooks:
    -   id: clang-format
        args: [--style=Google]
    -   id: clang-tidy
        args: [-checks=clang-diagnostic-return-type]
    -   id: oclint
        args: [-enable-clang-static-analyzer, -enable-global-analysis]
    -   id: uncrustify
    -   id: cppcheck
        args: [--enable=all]
